### ISSUE TITLE
Wireframes and User Stories

### ISSUE THREAD

**Issue by vnu** [WomenWhoCode/WomenWhoCodeSwift#1]
### Wireframes and User Stories

Please review the following doc /cc @codepathreview @codepath

https://docs.google.com/document/d/1bXAKSXT9Z5zZ12m3PrRsQzsAVzAYerGNs1mTTlD8Rwg/edit?usp=sharing

**Comment by sumade** [comment]
:+1: Thanks for submitting this and documenting your progress so far! Good to see you have an initial version of the wireframes complete as a starting point for your app. I'd recommend that you still use a wireframe tool since it tends to translate quicker to storyboard rather than your hand drawings.

Remember that by the end of your second sprint, we expect each team to have their core flows functionally complete (but rough), so this week (Sprint 1 review) your team should complete the first 50% of the core app functionality.

While building this app, try to keep in your mind the story for your app and what you need to have a polished demo. Be aggressive about which features you can scope into the first version for internal demo day. 

Question - will you be building a custom back end, or will you be using data provided by Women Who Code?

As far as the process goes, try to break down each of your stories/app features into smaller tasks (create issues) and assign it to your team members so that each team member has a clear idea on what they have to work on.

Excited to see what your group comes up with! Let us know what we can do to help.

**Comment by vnu** [comment]
@codepathreview Thanks for the feedback.
 We'll be using the parse for now, which we'll manually populate with data from WomenWhoCode. WomenWhoCode is currently building the API and I don't think it will be ready by Demo day.
