### ISSUE TITLE
[Intro to iOS] Week 5 Group Project - Women Who Code - Core Implementation Walkthrough

### ISSUE THREAD

**Issue by mahagovind** [WomenWhoCode/WomenWhoCodeSwift#30]
### Backend
We are integrating with Parse as backend.

### Tab 1: Events 
List of events that members can attend and its detail page

### Tab2: Connect
Search for other members

### Tab3: Profile
User profile with settings.

### Gif
![wwc_wk1](https://cloud.githubusercontent.com/assets/1395635/13588434/7e4af49c-e484-11e5-98be-983de0a6c465.gif)

### Login / Sign Up Gif
![wwc_login_video_walkthrough](https://cloud.githubusercontent.com/assets/16600833/13590218/eaf243d0-e492-11e5-96ae-9319e4e0fbb9.gif)

**Comment by mahagovind** [comment]
Please review /cc @codepathreview @codepath

**Comment by codepathreview** [comment]
:+1: Nice work creating wire-frames and creating stories for sprint 1. Great to see the basic screens and flow coming along well. Few notes to mention:

- Well created detailed stories/tasks on the project wiki.
- Consider diving a bigger parent task into a number of smaller subtasks - provides a better picture of the progress on the issue.
- Work load needs to be divided equally among all members of the team. This is critical in working as a team and also gives equal learning opportunity to everyone involved. Please make sure everyone contributes to the project in the next sprint. You can view [this graph](https://github.com/WomenWhoCode/WomenWhoCodeSwift/graphs/contributors) for more details.
- Consider creating tasks to complete the creation of your database schema and its respective models. Also, consider integrating with Parse, if you haven't already.
- Consider creating a project wiki so you can have a thorough documentation of all design decisions made during the project.
- Good to see that your team created regular commits to sync up your code to avoid having multiple conflicts at the end.
- Good job tasking to QA your work. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.


Good to see the basic flow coming along well. Please take notes of these points and improve upon the same in the next sprint. Look forward to the rest of the functionality and improvement on the core flows by the end of the Sprint 2 so you can have enough time to add UI polish and advanced nice-to-have features later on. It is those little extra things you do that make everything feel more polished and desirable to use.
