### ISSUE TITLE
[Intro to iOS] Week 6 Group Project (Women Who Code) : Core flows implementation 

### ISSUE THREAD

**Issue by mahagovind** [WomenWhoCode/WomenWhoCodeSwift#92]
### Tab 1: Timeline 
List of blogposts based on the area(s) of interest 

### Tab 2: Events 
List of events that members can attend and its detail page

### Tab 3: User Search
Search for other members and view their profile.

### Tab 4: Topics
List of topics that user can subscribe to.

### Tab 5: Profile
User profile with settings.

### Gif

![wwc_sprint2_walkthrough](https://cloud.githubusercontent.com/assets/16600833/13769355/2b2815f2-ea3c-11e5-9e5f-90062ae8abd9.gif)

**Comment by mahagovind** [comment]
Please review /cc @codepathreview @codepath

**Comment by codepathreview** [comment]
:+1: Nice work so far on the group project. Your team has made great progress in the last week. Hope you are proud of what you have achieved in ~6 weeks.

- Great to see that you took actions from the review comments from Sprint 1 and created milestones/issues for sprint 2.
- :+1: Good work implementing the core flows. You guys have made great progress in sprint 2 and it seems like most of your application logic is in place.
- Try to match your app with the mockups/wireframes as best as you can. Perhaps you might want to spend more time finishing up the remaining features and then add UI polish to the app.
- Good to see you have tasks/issues being worked on actively. Please consider regularly updating your readme file so you have a better idea of what's left to do.
- Good to see that you have already started adding UI polish to your app.
- Report the individual so he/she can receive proper guidance and doesn't miss out the opportunity to learn and contribute.
- Good to see that your team created regular check-ins to sync up your code to avoid having multiple errors at the end.
- Consider improving your test coverage by incorporating positive as well as negative testing to determine if your app handles improper user behavior correctly.

### Extras:

* Keep working on integrating the core flows and make sure all pieces fit together perfectly.
* Consult with your mentors to get their feedback as often as you can. Remember they are here to help!
* While working on polishing your app for next sprint, remember that your app follows the [Apple iOS Design Guidelines] (https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/).

Take time this week to clean up and polish your app. Generally, most of these tasks are small and easy, but go a long way in making an impact on how your app will get perceived. I would also encourage you to start thinking about coming up with a user story for the demo day. It is the apps with the most appealing story that gains the most attention on the demo day. Excited to see your progress next week! :tada:

**Comment by vnu** [comment]
Hi @codepathreview @codepath,

This is very in particular to "Report the individual so he/she can receive proper guidance and doesn't miss out the opportunity to learn and contribute."

 We've been contributing equally. I remember in our last review we were asked to check out this [this graph](https://github.com/WomenWhoCode/WomenWhoCodeSwift/graphs/contributors) page asking to equally contribute.

![image](https://cloud.githubusercontent.com/assets/1395635/13827366/53485356-eb79-11e5-8831-1f10c93e0c3c.png)

[Pulse](https://github.com/WomenWhoCode/WomenWhoCodeSwift/pulse) shows our equal contribution better.

The problem is, we've been following a system of issues and pull request and no body pushes directly to the master. For some reason, the graph page doesn't pick up the commits happening as part of merging pull requests and only direct pushes to master branch. The huge commits are our initial 2 commits of the project and the storyboards created by 1 person. 

I wanted to make sure the @codepath team is aware of this. Thanks :)
